2021-06-22 23:19:18,066 ERROR: Exception on /user/user1 [GET] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/dell/Documents/microblog/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/dell/Documents/microblog/app/templates/user.html", line 28, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2021-06-22 23:21:23,818 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:10:38,225 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:11:09,125 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:23:58,245 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:33:34,161 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 13:42:50,263 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:44]
2021-06-23 15:17:39,785 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 15:40:25,025 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 15:41:17,066 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 15:47:53,302 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 15:49:49,802 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 15:54:09,711 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:02:06,389 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 16:02:45,260 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 16:03:13,745 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:04:01,036 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:07:17,610 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 16:07:53,669 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:46]
2021-06-23 16:10:39,743 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:14:35,815 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:25:49,717 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:26:12,602 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:32:02,052 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:32:19,085 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:32:29,984 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:33:06,879 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 16:37:47,098 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:33:16,932 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:34:21,477 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:34:55,413 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:35:28,541 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:35:45,768 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:35:55,889 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:37:32,772 ERROR: Exception on /reset_password_request [POST] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
TypeError: send_password_reset_email() takes no arguments
2021-06-23 18:58:58,094 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 18:59:50,049 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:00:07,253 ERROR: Exception on /reset_password_request [POST] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
TypeError: send_password_reset_email() takes no arguments
2021-06-23 19:01:18,398 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:04:18,465 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:05:20,105 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:08:14,409 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:08:52,205 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
2021-06-23 19:09:02,489 ERROR: Exception on /reset_password_request [POST] [in /home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dell/Documents/microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/dell/Documents/microblog/app/routes.py", line 177, in reset_password_request
    send_password_reset_email(user)
TypeError: send_password_reset_email() takes no arguments
2021-06-23 19:13:08,288 INFO: Microblog startup [in /home/dell/Documents/microblog/app/__init__.py:45]
